#!/bin/sh

pip-compile --allow-unsafe --no-emit-index-url "$@"
cat >constraints.txt <<EOF
#
# This file is autogenerated by lock_requirements.sh
# To update, run:
#
#    sh lock_requirements.sh
#
EOF
sed -E -e 's/(\[.*\])//g' -e  '/^ *#/d' -e '/^$/d' requirements.txt >> constraints.txt
